name: Feature status report
description: Reports all features enabled on the agent

inputs:
  cilium-cli:
    required: false
    default: "/usr/local/bin/cilium"
    description: 'Path to the Cilium CLI binary'
  title:
    required: true
    description: 'Title for the summary description'
  json-filename:
    required: true
    description: 'Title for the JSON filename (without .json extension)'

runs:
  using: composite
  steps:
    - name: Report features enabled on the agent
      if: ${{ always() }}
      shell: bash
      run: |
        echo ""                                               >> "$GITHUB_STEP_SUMMARY"
        echo "## ${{ inputs.title }}"                         >> "$GITHUB_STEP_SUMMARY"
        echo ""                                               >> "$GITHUB_STEP_SUMMARY"
        echo "<details>"                                      >> "$GITHUB_STEP_SUMMARY"
        echo "  <summary>Click here to see</summary>"         >> "$GITHUB_STEP_SUMMARY"
        echo ""                                               >> "$GITHUB_STEP_SUMMARY"
        ${{ inputs.cilium-cli }} features status  -o markdown >> "$GITHUB_STEP_SUMMARY"
        echo "</details>"                                     >> "$GITHUB_STEP_SUMMARY"

        ${{ inputs.cilium-cli }} features status -o json --output-file="${{ inputs.json-filename }}.json"
