name: Image CI Cache Cleaner

# Any change in triggers needs to be reflected in the concurrency group.
on:
  workflow_dispatch:
  schedule:
    # Run the GC every Monday at 6am
    - cron: "0 6 * * 1"

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  setup-vars:
    name: Setup Variables
    runs-on: ubuntu-latest
    outputs:
      build-and-push-images: ${{ steps.vars.outputs.build-and-push-images }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Set up job variables
        id: vars
        run: |
          echo build-and-push-images=${BUILD_AND_PUSH_IMAGES} >> $GITHUB_OUTPUT

  cache-cleaner:
    name: Clean Image Cache
    needs: [ setup-vars ]
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          ${{ fromJSON(needs.setup-vars.outputs.build-and-push-images) }}

    steps:
      # Fetch the source code so that we can get the right cache key
      - name: Checkout Source Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false

      # Load Golang cache build from GitHub
      - name: Load ${{ matrix.name }} Golang cache build from GitHub
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        id: cache
        with:
          path: /tmp/.cache/${{ matrix.name }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ matrix.name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ matrix.name }}-
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-

      - name: Create ${{ matrix.name }} cache directory
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          mkdir -p /tmp/.cache/${{ matrix.name }}

      # Clean docker's golang's cache
      - name: Clean ${{ matrix.name }} Golang cache from GitHub
        shell: bash
        run: |
          rm -f /tmp/.cache/${{ matrix.name }}/go-build-cache.tar.gz
          rm -f /tmp/.cache/${{ matrix.name }}/go-pkg-cache.tar.gz
